/* Space & Matter tour — generated by admin.html */
window.TOUR = {
  "title": "Kavel 17.3, Amsterdam",
  "settings": {
    "fovMin": 35,
    "fovMax": 100,
    "yawLimited": true,
    "yawRange": 55,
    "pitchLimited": true,
    "pitchUp": 21,
    "pitchDown": 40
  },
  "scenes": [
    {
      "id": "kavel173-panorama-01",
      "name": "kavel173 panorama 01",
      "file": "panos/kavel173-panorama-01.webp?v=2",
      "front": {
        "yaw": 0.3,
        "pitch": -0.2,
        "fov": "max"
      },
      "settings": {
        "fovMin": 35,
        "fovMax": 100,
        "yawLimited": true,
        "yawRange": 55,
        "pitchLimited": true,
        "pitchUp": 21,
        "pitchDown": 40
      }
    }
  ]
};
