/* Space & Matter tour — generated by admin.html */
window.TOUR = {
  "title": "HBW75, Amsterdam",
  "settings": {
    "fovMin": 30,
    "fovMax": 90,
    "yawLimited": true,
    "yawRange": 30,
    "pitchLimited": true,
    "pitchUp": 15,
    "pitchDown": 15
  },
  "scenes": [
    {
      "id": "margriettoren-01",
      "name": "margriettoren 01",
      "file": "panos/margriettoren-01.jpg",
      "front": {
        "yaw": -1.8,
        "pitch": -2.9
      },
      "settings": {
        "fovMin": 10,
        "fovMax": 90,
        "yawLimited": true,
        "yawRange": 30,
        "pitchLimited": true,
        "pitchUp": 15,
        "pitchDown": 15
      }
    }
  ]
};
