/* Space & Matter tour — generated by admin.html */
window.TOUR = {
  "title": "CCH, Amsterdam",
  "settings": {
    "fovMin": 34,
    "fovMax": 90,
    "yawLimited": true,
    "yawRange": 90,
    "pitchLimited": true,
    "pitchUp": 14,
    "pitchDown": 10
  },
  "scenes": [
    {
      "id": "omval-panorama-01",
      "name": "omval panorama 01",
      "file": "panos/omval-panorama-01.webp",
      "front": {
        "yaw": -0.8,
        "pitch": -10.6
      },
      "settings": {
        "fovMin": 34,
        "fovMax": 90,
        "yawLimited": true,
        "yawRange": 90,
        "pitchLimited": true,
        "pitchUp": 14,
        "pitchDown": 10
      }
    },
    {
      "id": "omval-panorama-02",
      "name": "omval panorama 02",
      "file": "panos/omval-panorama-02.webp",
      "front": {
        "yaw": -178.6,
        "pitch": -1.5
      },
      "settings": {
        "fovMin": 50,
        "fovMax": 95,
        "yawLimited": false,
        "yawRange": 90,
        "pitchLimited": true,
        "pitchUp": 14,
        "pitchDown": 10
      }
    }
  ]
};
