/* Space & Matter tour — generated by admin.html */
window.TOUR = {
  "title": "Slotlaan, Zeist",
  "settings": {
    "fovMin": 45,
    "fovMax": 80,
    "yawLimited": true,
    "yawRange": 75,
    "pitchLimited": true,
    "pitchUp": 10,
    "pitchDown": 25
  },
  "scenes": [
    {
      "id": "zeist-panorama-03",
      "name": "zeist panorama 03",
      "file": "panos/zeist-panorama-03.jpg",
      "front": {
        "yaw": -8.7,
        "pitch": 2.9
      },
      "settings": {
        "fovMin": 45,
        "fovMax": 80,
        "yawLimited": true,
        "yawRange": 75,
        "pitchLimited": true,
        "pitchUp": 10,
        "pitchDown": 25
      }
    },
    {
      "id": "zeist-panorama-01",
      "name": "zeist panorama 01",
      "file": "panos/zeist-panorama-01.jpg",
      "front": {
        "yaw": 90.1,
        "pitch": -0.3
      },
      "settings": {
        "fovMin": 45,
        "fovMax": 80,
        "yawLimited": true,
        "yawRange": 190,
        "pitchLimited": true,
        "pitchUp": 10,
        "pitchDown": 25
      }
    },
    {
      "id": "zeist-panorama-02",
      "name": "Zeist Panorama 02",
      "file": "panos/zeist-panorama-02.jpg",
      "front": {
        "yaw": 90.9,
        "pitch": 0.4
      },
      "settings": {
        "fovMin": 45,
        "fovMax": 80,
        "yawLimited": true,
        "yawRange": 90,
        "pitchLimited": true,
        "pitchUp": 10,
        "pitchDown": 25
      }
    }
  ]
};
